### ISSUE TITLE
42 OAuth 로그인 구현

### ISSUE THREAD

**Issue by doo3721** [42-42-transcendence/ft_transcendence#34]
## TODO

- [x] 42 API 키 생성
- [x] User entity 42 OAuth token 추가
- [x] 백엔드 OAuth 메소드 생성
- [x] auth 모듈 생성
- [x] JWT 토큰 생성
- [x] db에 user 정보 저장
- [ ] ~~가입 확인시 user 정보 기준으로 확인하기~~

그 외 필요한 거 있으면 추가
